### ISSUE TITLE
cmake build live555失败

### ISSUE THREAD

**Issue by Lefttyre** [Cambricon/CNStream#5]
include/TLSState.hh:31:25: fatal error: openssl/ssl.h: No such file or directory

**Comment by st7109** [comment]
this is caused by the latest live555, as we known, live555 don't maintain a release notes.
for now, we provide a workaround for this.
1. sudo apt-get install libssl-dev
2. you can modify two makefile, add **ssl** dependency, just like below files:
     ./samples/demo/CMakeLists.txt
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wl,--no-as-needed")
   if(cnstream_build_integrated_lib)
-    target_link_libraries(${name} app-modules)
+    target_link_libraries(${name} app-modules ssl)
   else()
-    target_link_libraries(${name} app-rtsp_sink)
+    target_link_libraries(${name} app-rtsp_sink ssl)

     ./tools/inspect/CMakeLists.txt
   if(WITH_RTSP)
-    target_link_libraries(${name} ${Live555_LIBS} app-modules)
+    target_link_libraries(${name} ${Live555_LIBS} app-modules ssl)
   endif()
 else()
   set(module_list core)
@@ -67,6 +67,6 @@ else()
   endforeach()
   target_link_libraries(${name} ${depended_modules} dl glog pthread)
   if(WITH_RTSP)
-    target_link_libraries(${name} ${Live555_LIBS} app-rtsp_sink)
+    target_link_libraries(${name} ${Live555_LIBS} app-rtsp_sink ssl)
   endif()

we will fix this with fixed version after legal verification. thanks for you kindly remind.

**Comment by st7109** [comment]
[live555_workaround.zip](https://github.com/Cambricon/CNStream/files/3953686/live555_workaround.zip)

**Comment by Lefttyre** [comment]
fixed by b5ec6f8ba205745a35e851652bfde6c2ed322529
